#!/bin/bash
umount /cf && mount -o rw /cf
rm config.xml
echo "<?xml version="1.0"?>
<pfsense>
	<version>18.8</version>
	<lastchange/>
	<system>
		<optimization>normal</optimization>
		<hostname>pfSense</hostname>
		<dnsserver>8.8.8.8</dnsserver>
    		<dnsserver>1.1.1.1</dnsserver>
    <domain>localdomain</domain>
		<dnsallowoverride/>
		<group>
			<name>all</name>
			<description><![CDATA[All Users]]></description>
			<scope>system</scope>
			<gid>1998</gid>
			<member>0</member>
		</group>
		<group>
			<name>admins</name>
			<description><![CDATA[System Administrators]]></description>
			<scope>system</scope>
			<gid>1999</gid>
			<member>0</member>
			<priv>page-all</priv>
		</group>
		<user>
			<name>admin</name>
			<descr><![CDATA[System Administrator]]></descr>
			<scope>system</scope>
			<groupname>admins</groupname>
			<bcrypt-hash>$2y$10$5m8laVxFri0yht61js3TRuEr.iKfGnGbuFojIDNxQXwNF7BIsk7C</bcrypt-hash>
			<uid>0</uid>
			<priv>user-shell-access</priv>
		</user>
		<nextuid>2000</nextuid>
		<nextgid>2000</nextgid>
		<timeservers>0.pfsense.pool.ntp.org</timeservers>
		<webgui>
			<protocol>https</protocol>
			<loginautocomplete></loginautocomplete>
      <ssl-certef>5e4d23634cc7e</ssl-certref>
		</webgui>
		<disablenatreflection>yes</disablenatreflection>
		<disablesegmentationoffloading></disablesegmentationoffloading>
		<disablelargereceiveoffloading></disablelargereceiveoffloading>
		<ipv6allow></ipv6allow>
		<maximumtableentries>400000</maximumtableentries>
		<powerd_ac_mode>hadp</powerd_ac_mode>
		<powerd_battery_mode>hadp</powerd_battery_mode>
		<powerd_normal_mode>hadp</powerd_normal_mode>
		<bogons>
			<interval>monthly</interval>
		</bogons>
    <already_run_config_upgrade></already_run_config_upgrade>
    <timezone>America/Denver</timezone>
  </system>
	<interfaces>
		<WAN>
			<enable/>
			<if>em0</if>
			      <ipaddr>dhcp</ipaddr>
			      <ipaddrv6></ipaddrv6>
			      <gateway></gateway>
			      <blockpriv>on</blockpriv>
			      <blockbogons>on</blockbogons>
			      <media></media>
			      <mediaopt></mediaopt>
			      <dhcp6-duid></dhcp6-duid>
			      <dhcp6-ia-pd-len>0</dhcp6-is-pd-len>
			      <subnetv6></subnetv6>
			      <gatewayv6></gatewayv6>
		</WAN>
		<INTERNAL>
			<enable></enable>
			<if>em1</if>
			<ipaddr>192.168.171.2</ipaddr>
			<subnet>24</subnet>
			<ipaddrv6></ipaddrv6>
			<subnetv6></subnetv6>
			<media></media>
			<mediaopt></mediaopt>
			<track6-interface>WAN</track6-interface>
			<track6-p/fix-id>0</track6-prefix-id>
      <gateway></gateway>
      <gatewayv6></gatewayv6>
		</INTERNAL>
    <DMZ>
      <if>em2</if>
      <descr><![CDATA[DMZ]]></descr>
      <ipaddr>192.168.91.2</ipaddr>
      <subnet>24</subnet>
      <gateway></gateway>
      <ipaddrv6></ipaddrv6>
      <subnetv6></subnetv6>
      <gatewayv6></gatewayv6>
      <enable></enable>
    </DMZ>
	</interfaces>
	<staticroutes></staticroutes>
	<dhcpd>
		<INTERNAL>
			<range>
				<enable></enable>
        <from>192.168.171.100</from>
				<to>192.168.171.150</to>
			</range>
		</INTERNAL>
    <DMZ>
      <enable></enable>
			<range>
				<from>192.168.171.100</from>
				<to>192.168.171.150</to>
			</range>
	</dhcpd>
	<dhcpdv6>
		<INTERNAL>
			<enable/>
			<range>
				<from>::1000</from>
				<to>::2000</to>
			</range>
			<ramode>assist</ramode>
			<rapriority>medium</rapriority>
		</INTERNAL>
		<DMZ>
			<enable/>
			<range>
				<from>::1000</from>
				<to>::2000</to>
			</range>
			<ramode>assist</ramode>
			<rapriority>medium</rapriority>
		</DMZ>
	</dhcpdv6>
	<snmpd>
		<syslocation></syslocation>
		<syscontact></syscontact>
		<rocommunity>public</rocommunity>
	</snmpd>
	<diag>
		<ipv6nat>
			<ipaddr></ipaddr>
		</ipv6nat>
	</diag>
	<syslog>
		<filterdescriptions>1</filterdescriptions>
	</syslog>
	<nat>
		<outbound>
			<mode>automatic</mode>
		</outbound>
	</nat>
	<filter>
		<rule>
      <id></id>
      <tracker>1582142671</tracker>
			<type>block</type>
      <interface>WAN</interface>
			<ipprotocol>inet46</ipprotocol>
      <tag></tag>
      <tagged></tagged>
      <max></max
      <max-src-nodes></max-src-nodes>
      <max-src-conn></max-src-conn>
      <max-src-states></max-src-states>
      <statetimeout></statetimeout>
			<statetype><![CDATA[keep state]]></statetype>
      <os</os>
			<source>
				<any></any>
			</source>
			<destination>
				<port>1-79</port>
        <port>81-65535</port>
			</destination>
      <log></log>
      <descr></descr>
      <created> 
        <time>1582142671</time>
        <username>admin@192.168.171.100 (Local Database) </username>
       </created>
       <updated>
        <time>1582142835</time>
        <username>admin@192.168.171.100 (Local Database) </username>
		</rule>
		<rule>
			<type>pass</type>
			<ipprotocol>inet</ipprotocol>
			<descr><![CDATA[Default allow INTERNAL IPv6 to any rule]]></descr>
			<interface>INTERNAL</interface>
			<tracker>0100000101</tracker>
			<source>
				<network>INTERNAL</network>
			</source>
			<destination>
				<any></any>
			</destination>
		</rule>
    <separator>
      <WAN></WAN>
    </separator>
	</filter>
	<shaper>
  </shaper>
	<ipsec></ipsec>
	<aliases></aliases>
	<proxyarp></proxyarp>
	<cron>
		<item>
			<minute>*/1</minute>
			<hour>*</hour>
			<mday>*</mday>
			<month>*</month>
			<wday>*</wday>
			<who>root</who>
			<command>/usr/sbin/newsyslog</command>
		</item>
		<item>
			<minute>1</minute>
			<hour>3</hour>
			<mday>*</mday>
			<month>*</month>
			<wday>*</wday>
			<who>root</who>
			<command>/etc/rc.periodic daily</command>
		</item>
		<item>
			<minute>15</minute>
			<hour>4</hour>
			<mday>*</mday>
			<month>*</month>
			<wday>6</wday>
			<who>root</who>
			<command>/etc/rc.periodic weekly</command>
		</item>
		<item>
			<minute>30</minute>
			<hour>5</hour>
			<mday>1</mday>
			<month>*</month>
			<wday>*</wday>
			<who>root</who>
			<command>/etc/rc.periodic monthly</command>
		</item>
		<item>
			<minute>1,31</minute>
			<hour>0-5</hour>
			<mday>*</mday>
			<month>*</month>
			<wday>*</wday>
			<who>root</who>
			<command>/usr/bin/nice -n20 adjkerntz -a</command>
		</item>
		<item>
			<minute>1</minute>
			<hour>3</hour>
			<mday>1</mday>
			<month>*</month>
			<wday>*</wday>
			<who>root</who>
			<command>/usr/bin/nice -n20 /etc/rc.update_bogons.sh</command>
		</item>
		<item>
			<minute>1</minute>
			<hour>1</hour>
			<mday>*</mday>
			<month>*</month>
			<wday>*</wday>
			<who>root</who>
			<command>/usr/bin/nice -n20 /etc/rc.dyndns.update</command>
		</item>
		<item>
			<minute>*/60</minute>
			<hour>*</hour>
			<mday>*</mday>
			<month>*</month>
			<wday>*</wday>
			<who>root</who>
			<command>/usr/bin/nice -n20 /usr/local/sbin/expiretable -v -t 3600 virusprot</command>
		</item>
		<item>
			<minute>30</minute>
			<hour>12</hour>
			<mday>*</mday>
			<month>*</month>
			<wday>*</wday>
			<who>root</who>
			<command>/usr/bin/nice -n20 /etc/rc.update_urltables</command>
		</item>
		<item>
			<minute>1</minute>
			<hour>0</hour>
			<mday>*</mday>
			<month>*</month>
			<wday>*</wday>
			<who>root</who>
			<command>/usr/bin/nice -n20 /etc/rc.update_pkg_metadata</command>
		</item>
	</cron>
	<wol/>
	<rrd>
		<enable/>
	</rrd>
	<widgets>
		<sequence>system_information:col1:show,netgate_services_and_support:col2:show,interfaces:col2:show</sequence>
		<period>10</period>
	</widgets>
	<openvpn/>
	<dnshaper/>
	<unbound>
		<enable/>
		<dnssec/>
		<active_interface/>
		<outgoing_interface/>
		<custom_options/>
		<hideidentity/>
		<hideversion/>
		<dnssecstripped/>
	</unbound>
</pfsense>" > config.xml

